name       : gst-validate
version    : 1.16.3
release    : 14
source     :
    - https://gstreamer.freedesktop.org/src/gst-validate/gst-validate-1.16.3.tar.xz : c2064e887324af6aa476ca669234936711f253b29042f617f1d9f2597c4bf92b
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : GStreamer Validate testing Framework
description: |
    The goal of GstValidate is to be able to detect when elements are not
    behaving as expected and report it to the user so he knows how things
    are supposed to work inside a GstPipeline. In the end, fixing issues
    found by the tool will ensure that all elements behave all together in
    the expected way.
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
rundeps    :
    - gstreamer-1.0
    - gstreamer-1.0-plugins-base
setup      : |
    %configure --disable-static \
               --with-package-name="GSt-validate ${version} Solus" \
               --with-package-origin="https://getsol.us"
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
