name       : gst-validate
version    : 1.12.4
release    : 2
source     :
    - https://gstreamer.freedesktop.org/src/gst-validate/gst-validate-1.12.4.tar.xz : f9da9dfe6e5d6f5ba3b38c5752b42d3f927715904942b405c2924d3cb77afba1
license    : LGPL-2.1
component  : multimedia.gstreamer
summary    : GStreamer Validate testing Framework
description: |
    The goal of GstValidate is to be able to detect when elements are not
    behaving as expected and report it to the user so he knows how things
    are supposed to work inside a GstPipeline. In the end, fixing issues
    found by the tool will ensure that all elements behave all together in
    the expected way.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
rundeps    :
    - gstreamer-1.0
    - gstreamer-1.0-plugins-base
setup      : |
    %configure --disable-static \
               --with-package-name="GSt-validate ${version} Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
